use music_db;

insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (1, 'moderator', 'blandit non interdum', 'non mauris morbi non', 4524);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (2, 'Function-based', 'nec molestie sed justo', 'semper rutrum nulla nunc', 4501);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (3, 'matrix', 'iaculis congue vivamus metus arcu', 'morbi vestibulum velit id pretium', 4328);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (4, 'matrix', 'volutpat dui maecenas tristique est', 'pretium quis lectus', 9466);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (5, 'forecast', 'vivamus in felis eu sapien', 'interdum venenatis turpis enim', 249);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (6, 'holistic', 'et magnis dis parturient montes', 'consequat nulla nisl', 5343);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (7, 'scalable', 'vel lectus in quam', 'vestibulum velit id pretium', 1829);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (8, 'radical', 'est phasellus sit', 'amet justo morbi ut odio', 8938);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (9, 'Robust', 'vivamus metus arcu', 'pretium iaculis diam', 8636);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (10, 'productivity', 'sapien non mi integer', 'posuere cubilia curae', 499);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (11, 'Grass-roots', 'non mi integer', 'at diam nam', 7434);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (12, 'national', 'tincidunt eu felis fusce posuere', 'condimentum id luctus nec molestie', 5540);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (13, 'Organic', 'congue etiam justo etiam', 'tortor risus dapibus augue', 4952);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (14, 'responsive', 'aliquet maecenas leo odio condimentum', 'in felis donec', 5087);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (15, 'matrix', 'sed magna at nunc', 'duis faucibus accumsan odio', 2453);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (16, 'throughput', 'quis odio consequat varius', 'vitae quam suspendisse potenti nullam', 7768);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (17, 'definition', 'sodales scelerisque mauris', 'felis ut at', 1618);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (18, 'installation', 'integer aliquet massa', 'nec nisi volutpat eleifend donec', 5510);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (19, 'composite', 'cras pellentesque volutpat dui maecenas', 'varius nulla facilisi cras non', 4682);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (20, 'architecture', 'diam erat fermentum', 'vestibulum sagittis sapien cum', 309);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (21, 'solution', 'ac leo pellentesque ultrices mattis', 'cras non velit nec', 8734);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (22, 'definition', 'mauris non ligula pellentesque', 'massa donec dapibus duis at', 1903);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (23, 'leading edge', 'lobortis est phasellus sit', 'interdum mauris non ligula pellentesque', 8139);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (24, 'capacity', 'penatibus et magnis', 'at nulla suspendisse potenti', 8992);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (25, 'didactic', 'nascetur ridiculus mus', 'id turpis integer', 4382);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (26, 'mission-critical', 'dapibus nulla suscipit ligula in', 'porttitor lacus at', 5077);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (27, 'incremental', 'euismod scelerisque quam turpis', 'lectus suspendisse potenti in eleifend', 6737);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (28, 'Right-sized', 'morbi ut odio cras', 'enim blandit mi', 6127);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (29, 'encryption', 'odio odio elementum eu', 'non mauris morbi non', 7514);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (30, 'client-server', 'rutrum nulla nunc purus', 'aenean auctor gravida', 1143);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (31, 'Distributed', 'dapibus dolor vel est donec', 'morbi porttitor lorem id', 2309);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (32, 'radical', 'non mattis pulvinar nulla', 'nulla ultrices aliquet maecenas', 9361);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (33, 'explicit', 'cras mi pede', 'convallis eget eleifend', 8368);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (34, 'Function-based', 'vestibulum vestibulum ante', 'integer ac leo pellentesque', 2558);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (35, 'upward-trending', 'erat tortor sollicitudin mi', 'ridiculus mus etiam', 5612);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (36, 'circuit', 'et ultrices posuere cubilia curae', 'quam sollicitudin vitae consectetuer', 3481);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (37, 'Synergistic', 'ultrices vel augue vestibulum ante', 'amet diam in magna', 373);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (38, 'Streamlined', 'posuere cubilia curae', 'rutrum neque aenean', 1565);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (39, 'eco-centric', 'ante vestibulum ante ipsum', 'ultrices mattis odio donec vitae', 7735);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (40, 'parallelism', 'enim leo rhoncus sed vestibulum', 'semper interdum mauris ullamcorper', 762);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (41, 'neutral', 'eu orci mauris lacinia', 'ipsum dolor sit', 9635);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (42, 'Extended', 'massa volutpat convallis morbi odio', 'ornare consequat lectus in', 3075);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (43, 'zero defect', 'et commodo vulputate justo', 'non ligula pellentesque', 2837);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (44, 'artificial intelligence', 'turpis enim blandit mi', 'sit amet sapien dignissim', 4359);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (45, 'Re-contextualized', 'elementum in hac', 'at ipsum ac tellus', 4828);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (46, 'even-keeled', 'porta volutpat quam pede lobortis', 'etiam justo etiam pretium iaculis', 4752);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (47, 'attitude-oriented', 'a ipsum integer', 'congue vivamus metus', 2069);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (48, 'moderator', 'neque vestibulum eget vulputate ut', 'proin leo odio porttitor', 3068);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (49, 'methodical', 'in faucibus orci luctus', 'diam in magna bibendum', 5829);
insert into DeimosPlayer (id, artist_name, record_name, song_name, duration) values (50, 'product', 'amet eleifend pede', 'sed justo pellentesque viverra', 4863);
